name: Event Deep Dive
on: 
jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - name: Output Issues
        run: echo " ${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm run test
      - name: Build Code
        run: npm run build
